services:
  postgres:
    image: postgres:16
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
  
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
      start_interval: 1s

  redis:
    image: redis:8-alpine
    container_name: redis
    
    volumes:
      - redis_data:/data
    
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
  

  backend_application:
    build: /home/lisiks/Рабочий стол/College/4 Курс/Application
    container_name: backend_container
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}

      APP_PORT: ${APP_PORT}
      APP_RELOAD: ${APP_RELOAD}
      APP_SU_LOGIN: ${APP_SU_LOGIN}
      APP_SU_PASSWORD: ${APP_SU_PASSWORD}
      APP_NAME: ${APP_NAME}
      APP_DESCRIPTION: ${APP_DESCRIPTION}
      APP_VERSION: ${APP_VERSION}

      REDIS_PORT: ${REDIS_PORT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_DB: ${REDIS_DB}

      PAGINATION_BOOKS_PAGE_SIZE: ${PAGINATION_BOOKS_PAGE_SIZE}
      PAGINATION_USERS_PAGE_SIZE: ${PAGINATION_USERS_PAGE_SIZE}
      PAGINATION_ORDERS_PAGE_SIZE: ${PAGINATION_ORDERS_PAGE_SIZE}

      SESSION_TTL: ${SESSION_TTL}
      SESSION_HASH_KEY: ${SESSION_HASH_KEY}
      SESSION_COOKIE_KEY: ${SESSION_COOKIE_KEY}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      redis: 
        condition: service_healthy
      postgres:
        condition: service_healthy
    pre_start:
      - command: ["alembic", "upgrade", "head"]
      
  
volumes:
  pgdata:
  redis_data: