"""updating_shemas_creating_indexes_and_fk

Revision ID: 06dbabd2b221
Revises: 1e49f1b9da69
Create Date: 2026-10-07 19:09:29.668386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06dbabd2b221'
down_revision: Union[str, Sequence[str], None] = '1e49f1b9da69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('fio_idx', 'authors', ['f', 'i', 'o'], unique=False)
    op.alter_column('books', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('books', 'jahnre_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('authors_id_fk'), 'books', type_='foreignkey')
    op.drop_constraint(op.f('jahnres_id_fk'), 'books', type_='foreignkey')
    op.create_foreign_key('jahnres_id_fk', 'books', 'jahnres', ['jahnre_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key('authors_id_fk', 'books', 'authors', ['author_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_index(op.f('ix_comments_datetime'), 'comments', ['datetime'], unique=False)
    op.create_index(op.f('ix_orders_datetime'), 'orders', ['datetime'], unique=False)
    op.drop_constraint(op.f('address_uq'), 'shops', type_='unique')
    op.create_index('address_idx', 'shops', ['town', 'street', 'housing'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('address_idx', table_name='shops')
    op.create_unique_constraint(op.f('address_uq'), 'shops', ['town', 'street', 'housing'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_orders_datetime'), table_name='orders')
    op.drop_index(op.f('ix_comments_datetime'), table_name='comments')
    op.drop_constraint('authors_id_fk', 'books', type_='foreignkey')
    op.drop_constraint('jahnres_id_fk', 'books', type_='foreignkey')
    op.create_foreign_key(op.f('jahnres_id_fk'), 'books', 'jahnres', ['jahnre_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(op.f('authors_id_fk'), 'books', 'authors', ['author_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.alter_column('books', 'jahnre_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('books', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('fio_idx', table_name='authors')
    # ### end Alembic commands ###
