"""modify book table

Revision ID: 1e49f1b9da69
Revises: b152b49828ba
Create Date: 2026-09-20 22:44:41.867449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e49f1b9da69'
down_revision: Union[str, Sequence[str], None] = 'b152b49828ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'demo_file_path',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'demo_file_path',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
