"""modifing authors and shops tables

Revision ID: b152b49828ba
Revises: fc1e3c160487
Create Date: 2026-09-20 16:43:10.177682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b152b49828ba'
down_revision: Union[str, Sequence[str], None] = 'fc1e3c160487'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('fio_idx'), table_name='authors')
    op.alter_column('shops', 'housing',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=6),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shops', 'housing',
               existing_type=sa.String(length=6),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_index(op.f('fio_idx'), 'authors', ['f', 'i', 'o'], unique=False)
    # ### end Alembic commands ###
