"""Delete book jahnres m:m

Revision ID: 36fa5af386e4
Revises: 44dc28e52d4c
Create Date: 2026-09-20 06:27:31.245309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36fa5af386e4'
down_revision: Union[str, Sequence[str], None] = '44dc28e52d4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books_jahnres')
    op.add_column('books', sa.Column('jahnre_id', sa.Integer(), nullable=True))
    op.create_foreign_key('jahnres_id_fk', 'books', 'jahnres', ['jahnre_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('jahnres_id_fk', 'books', type_='foreignkey')
    op.drop_column('books', 'jahnre_id')
    op.create_table('books_jahnres',
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('jahnre_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('book_id_fk'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['jahnre_id'], ['jahnres.id'], name=op.f('jahnre_id_fk'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_id', 'jahnre_id', name=op.f('books_jahnres_pk'))
    )
    # ### end Alembic commands ###
