"""Chanhe Authors idx

Revision ID: 559fa7dcfc92
Revises: 36fa5af386e4
Create Date: 2026-09-20 14:26:27.786872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '559fa7dcfc92'
down_revision: Union[str, Sequence[str], None] = '36fa5af386e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_authors_f'), table_name='authors')
    op.create_index('fio_idx', 'authors', ['f', 'i', 'o'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('fio_idx', table_name='authors')
    op.create_index(op.f('ix_authors_f'), 'authors', ['f'], unique=False)
    # ### end Alembic commands ###
