"""modifying shops table

Revision ID: fc1e3c160487
Revises: 559fa7dcfc92
Create Date: 2026-09-20 15:12:32.046028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc1e3c160487'
down_revision: Union[str, Sequence[str], None] = '559fa7dcfc92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('phone', sa.String(length=20), nullable=False))
    op.add_column('shops', sa.Column('town', sa.String(length=100), nullable=False))
    op.add_column('shops', sa.Column('street', sa.String(length=100), nullable=False))
    op.add_column('shops', sa.Column('housing', sa.Integer(), nullable=False))
    op.create_unique_constraint('address_uq', 'shops', ['town', 'street', 'housing'])
    op.create_unique_constraint(None, 'shops', ['phone'])
    op.drop_column('shops', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('address', sa.TEXT(), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'shops', type_='unique')
    op.drop_constraint('address_uq', 'shops', type_='unique')
    op.drop_column('shops', 'housing')
    op.drop_column('shops', 'street')
    op.drop_column('shops', 'town')
    op.drop_column('shops', 'phone')
    # ### end Alembic commands ###
